In [1]:
#Import required packages 

import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
#load dataset

In [3]:
a_dataset = pd.read_csv("train_data.csv")

In [4]:
#Print dataset information

In [5]:
a_dataset['TypeOfAdmission'].unique()

array(['Newborn', 'Emergency', 'Elective', 'Urgent'], dtype=object)

In [6]:
a_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59966 entries, 0 to 59965
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   ID                            59966 non-null  int64 
 1   HealthServiceArea             59966 non-null  object
 2   Gender                        59966 non-null  object
 3   Race                          59966 non-null  object
 4   TypeOfAdmission               59966 non-null  object
 5   CCSProcedureCode              59966 non-null  int64 
 6   APRSeverityOfIllnessCode      59966 non-null  int64 
 7   PaymentTypology               59966 non-null  object
 8   BirthWeight                   59966 non-null  int64 
 9   EmergencyDepartmentIndicator  59966 non-null  object
 10  AverageCostInCounty           59966 non-null  int64 
 11  AverageChargesInCounty        59966 non-null  int64 
 12  AverageCostInFacility         59966 non-null  int64 
 13  AverageChargesIn

In [7]:
a_dataset['PaymentTypology'].unique()

array(['Medicaid', 'Private Health Insurance', 'Blue Cross/Blue Shield',
       'Self-Pay', 'Managed Care, Unspecified', 'Miscellaneous/Other',
       'Federal/State/Local/VA', 'Medicare', 'Unknown'], dtype=object)

In [8]:
# Remove ID 

In [9]:
a_dataset = a_dataset.drop(columns = ['ID'])

In [10]:
a_dataset = a_dataset.drop(columns = ['HealthServiceArea'])

In [11]:
print(a_dataset)

      Gender                    Race TypeOfAdmission  CCSProcedureCode  \
0          F              Other Race         Newborn               228   
1          M  Black/African American         Newborn               228   
2          M              Other Race         Newborn               220   
3          F              Other Race         Newborn                 0   
4          F              Other Race         Newborn               228   
...      ...                     ...             ...               ...   
59961      M  Black/African American         Newborn               115   
59962      M                   White         Newborn               115   
59963      M                   White         Newborn               115   
59964      M                   White         Newborn                -1   
59965      F                   White         Newborn               231   

       APRSeverityOfIllnessCode           PaymentTypology  BirthWeight  \
0                             1      

In [12]:
# One-hot encoding, specifically Gender(M, F, U), Race(Black/African American, Multi, Other Race, Unkown, White, Other Race),  TypeOfAdmission(Elective, Emergency, Newborn, Not Available, Trauma, Urgent)
# APRSeverityOfIllnessCode(Minor (1), Moderate (2),   Major (3), Extreme (4)), 
#PaymentTypology('Medicaid', 'Blue Cross/Blue Shield', 'Private Health Insurance', 'Medicare', 'Managed Care, Unspecified', 'Self-Pay', 'Unknown', 'Federal/State/Local/VA', 'Miscellaneous/Other','Department of Corrections')
#EmergencyDepartmentIndicator(Y, N) 

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
OneHotEncoder_Gender = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_Gender.fit(a_dataset[['Gender']])

onehot_ = OneHotEncoder_Gender.transform(a_dataset[['Gender']]).toarray()

print(onehot_)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [15]:
print(onehot_.shape, OneHotEncoder_Gender.categories_)

(59966, 3) [array(['F', 'M', 'U'], dtype=object)]


In [16]:
# Begin One hot encoding for 'Gender'

In [17]:
colname = 'Gender'
for i in range(len(OneHotEncoder_Gender.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_Gender.categories_[0][i])] = onehot_[:,i]
    


In [18]:
a_dataset.shape

(59966, 17)

In [19]:
a_dataset = a_dataset.drop(columns = ['Gender'])

In [20]:
a_dataset.shape

(59966, 16)

In [21]:
a_dataset['TypeOfAdmission'].unique()

array(['Newborn', 'Emergency', 'Elective', 'Urgent'], dtype=object)

In [22]:
## Do every other categorical column

In [23]:
OneHotEncoder_TypeOfAdmission = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_TypeOfAdmission.fit(a_dataset[['TypeOfAdmission']])

onehot_ = OneHotEncoder_TypeOfAdmission.transform(a_dataset[['TypeOfAdmission']]).toarray()

colname = 'TypeOfAdmission'
for i in range(len(OneHotEncoder_TypeOfAdmission.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_TypeOfAdmission.categories_[0][i])] = onehot_[:,i]
    

In [24]:
print(onehot_.shape, OneHotEncoder_TypeOfAdmission.categories_)


(59966, 4) [array(['Elective', 'Emergency', 'Newborn', 'Urgent'], dtype=object)]


In [25]:
a_dataset = a_dataset.drop(columns = ['TypeOfAdmission'])

In [26]:
OneHotEncoder_Race = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_Race.fit(a_dataset[['Race']])

onehot_ = OneHotEncoder_Race.transform(a_dataset[['Race']]).toarray()

colname = 'Race'
for i in range(len(OneHotEncoder_Race.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_Race.categories_[0][i])] = onehot_[:,i]
    


In [27]:
a_dataset["CCSProcedureCode"].unique()

array([228, 220,   0, 231, 115,  -1, 216])

In [28]:
a_dataset = a_dataset.drop(columns = ['Race'])

In [29]:
OneHotEncoder_CCSProcedureCode = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_CCSProcedureCode.fit(a_dataset[['CCSProcedureCode']])

onehot_ = OneHotEncoder_CCSProcedureCode.transform(a_dataset[['CCSProcedureCode']]).toarray()

colname = 'CCSProcedureCode'
for i in range(len(OneHotEncoder_CCSProcedureCode.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_CCSProcedureCode.categories_[0][i])] = onehot_[:,i]

a_dataset = a_dataset.drop(columns = ['CCSProcedureCode'])

In [30]:
a_dataset

APRSeverityOfIllnessCode           PaymentTypology  BirthWeight  \
0                             1                  Medicaid         3700   
1                             1                  Medicaid         2900   
2                             1  Private Health Insurance         3200   
3                             1  Private Health Insurance         3300   
4                             1                  Medicaid         2600   
...                         ...                       ...          ...   
59961                         1    Blue Cross/Blue Shield         3600   
59962                         2    Blue Cross/Blue Shield         3300   
59963                         2    Blue Cross/Blue Shield         3400   
59964                         2                  Medicaid         3100   
59965                         2    Blue Cross/Blue Shield         3900   

      EmergencyDepartmentIndicator  AverageCostInCounty  \
0                                N                 2611   
1                                N                 3242   
2                                N                 3155   
3                                N                 3155   
4                                N                 2611   
...                            ...                  ...   
59961                            N                 1826   
59962                            N                 1826   
59963                            N                 1826   
59964                            N                 1826   
59965                            N                 1826   

       AverageChargesInCounty  AverageCostInFacility  \
0                        9227                   1751   
1                        8966                   3338   
2                       11381                   4980   
3                       11381                   5826   
4                        9227                   6000   
...                       ...                    ...   
59961                    4190                   1551   
59962                    4190                   1551   
59963                    4190                   1551   
59964                    4190                   1551   
59965                    4190                   1551   

       AverageChargesInFacility  AverageIncomeInZipCode  LengthOfStay  ...  \
0                          8951                      45             1  ...   
1                          6409                      34             1  ...   
2                          9323                      45             1  ...   
3                         15680                      59             1  ...   
4                         14344                      59             1  ...   
...                         ...                     ...           ...  ...   
59961                      3715                      36             4  ...   
59962                      3715                      55             6  ...   
59963                      3715                      55             4  ...   
59964                      3715                      55             4  ...   
59965                      3715                      36             4  ...   

       Race_Multi-racial  Race_Other Race  Race_White  CCSProcedureCode_-1  \
0                    0.0              1.0         0.0                  0.0   
1                    0.0              0.0         0.0                  0.0   
2                    0.0              1.0         0.0                  0.0   
3                    0.0              1.0         0.0                  0.0   
4                    0.0              1.0         0.0                  0.0   
...                  ...              ...         ...                  ...   
59961                0.0              0.0         0.0                  0.0   
59962                0.0              0.0         1.0                  0.0   
59963                0.0              0.0         1.0                  0.0   
59964              

In [31]:
OneHotEncoder_EmergencyDepartmentIndicator = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_EmergencyDepartmentIndicator.fit(a_dataset[['EmergencyDepartmentIndicator']])

onehot_ = OneHotEncoder_EmergencyDepartmentIndicator.transform(a_dataset[['EmergencyDepartmentIndicator']]).toarray()

colname = 'EmergencyDepartmentIndicator'
for i in range(len(OneHotEncoder_EmergencyDepartmentIndicator.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_EmergencyDepartmentIndicator.categories_[0][i])] = onehot_[:,i]

a_dataset = a_dataset.drop(columns = ['EmergencyDepartmentIndicator'])

In [32]:
OneHotEncoder_PaymentTypology = OneHotEncoder(handle_unknown ='ignore')
OneHotEncoder_PaymentTypology.fit(a_dataset[['PaymentTypology']])

onehot_ = OneHotEncoder_PaymentTypology.transform(a_dataset[['PaymentTypology']]).toarray()

colname = 'PaymentTypology'
for i in range(len(OneHotEncoder_PaymentTypology.categories_[0])):
    a_dataset[colname + '_' + str(OneHotEncoder_PaymentTypology.categories_[0][i])] = onehot_[:,i]

a_dataset = a_dataset.drop(columns = ['PaymentTypology'])

In [34]:
a_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59966 entries, 0 to 59965
Data columns (total 37 columns):
 #   Column                                     Non-Null Count  Dtype  
---  ------                                     --------------  -----  
 0   APRSeverityOfIllnessCode                   59966 non-null  int64  
 1   BirthWeight                                59966 non-null  int64  
 2   AverageCostInCounty                        59966 non-null  int64  
 3   AverageChargesInCounty                     59966 non-null  int64  
 4   AverageCostInFacility                      59966 non-null  int64  
 5   AverageChargesInFacility                   59966 non-null  int64  
 6   AverageIncomeInZipCode                     59966 non-null  int64  
 7   LengthOfStay                               59966 non-null  int64  
 8   Gender_F                                   59966 non-null  float64
 9   Gender_M                                   59966 non-null  float64
 10  Gender_U              